export type LearningLevel = "Beginner" | "Intermediate" | "Advanced";

export type ComponentCategory =
  | "Microcontrollers"
  | "Prototyping"
  | "Basic electronics"
  | "Inputs"
  | "Sensors"
  | "Displays"
  | "Actuators"
  | "Drivers"
  | "Communication"
  | "Power"
  | "Mechanical";

export type StemComponent = {
  slug: string;
  name: string;
  category: ComponentCategory;
  summary: string;
  voltage: string;
  interface: string;
  pins: string;
  safety: string;
  beginnerTip: string;
  compatibleBoards: string[];
};

export type BuildProject = {
  slug: string;
  title: string;
  level: LearningLevel;
  area: "Electronics" | "Sensors" | "Robotics" | "IoT" | "Programming";
  summary: string;
  outcome: string;
  minutes: number;
  boards: string[];
  required: string[];
  optional?: string[];
  skills: string[];
  firstTest: string;
  troubleshoot: string[];
  improve: string[];
};

const allBoards = ["Arduino Uno", "Arduino Nano", "ESP32", "Raspberry Pi Pico", "BBC micro:bit", "STM32"];

export const componentCatalog: StemComponent[] = [
  { slug:"arduino-uno", name:"Arduino Uno", category:"Microcontrollers", summary:"A beginner-friendly 5 V ATmega328P development board used for electronics and robotics.", voltage:"5 V logic", interface:"USB + GPIO / ADC / UART / I2C / SPI", pins:"Digital D0–D13, analog A0–A5; confirm the board reference before wiring.", safety:"Do not power motors directly from GPIO. Keep pin current and supply voltage within board limits.", beginnerTip:"Start with one LED or button before adding sensors and motors.", compatibleBoards:["Arduino Uno"] },
  { slug:"arduino-nano", name:"Arduino Nano", category:"Microcontrollers", summary:"A compact Arduino-compatible ATmega328P board for breadboard projects.", voltage:"5 V logic on common classic Nano boards", interface:"USB + GPIO / ADC / UART / I2C / SPI", pins:"Pin layout varies by Nano generation; check the exact board.", safety:"Confirm the exact Nano version and logic voltage before connecting modules.", beginnerTip:"Treat it like a smaller Uno, but verify pin labels first.", compatibleBoards:["Arduino Nano"] },
  { slug:"arduino-mega", name:"Arduino Mega 2560", category:"Microcontrollers", summary:"A larger Arduino board with many GPIO pins and serial ports for bigger builds.", voltage:"5 V logic", interface:"USB + GPIO / ADC / UART / I2C / SPI", pins:"Many digital, analog and serial pins; use the official pinout for the exact board.", safety:"Do not assume every peripheral pin is interchangeable. Keep loads off GPIO.", beginnerTip:"Useful when a project outgrows the Uno's pin count.", compatibleBoards:["Arduino Mega 2560"] },
  { slug:"esp32", name:"ESP32", category:"Microcontrollers", summary:"A 3.3 V microcontroller family with built-in Wi-Fi and Bluetooth.", voltage:"3.3 V logic", interface:"Wi-Fi / Bluetooth / GPIO / ADC / UART / I2C / SPI", pins:"GPIO availability varies by ESP32 board; some pins are input-only or boot-sensitive.", safety:"ESP32 GPIO is not generally 5 V tolerant. Level-shift 5 V signals where required.", beginnerTip:"Use it when you want connectivity after you understand the basic circuit.", compatibleBoards:["ESP32"] },
  { slug:"esp32-cam", name:"ESP32-CAM", category:"Microcontrollers", summary:"An ESP32-based camera board for image and connected-camera experiments.", voltage:"3.3 V logic; board power requirements vary", interface:"Camera + Wi-Fi / GPIO / serial programming", pins:"Limited free GPIO because many pins are used by the camera or SD interface.", safety:"Use a stable power source and do not apply 5 V directly to 3.3 V GPIO.", beginnerTip:"Start after you are comfortable with ESP32 upload and power troubleshooting.", compatibleBoards:["ESP32"] },
  { slug:"raspberry-pi-pico", name:"Raspberry Pi Pico", category:"Microcontrollers", summary:"A 3.3 V RP2040 board suitable for MicroPython and C/C++ learning.", voltage:"3.3 V logic", interface:"USB + GPIO / ADC / UART / I2C / SPI / PWM", pins:"GP pins plus ADC pins; check the Pico pinout.", safety:"GPIO is 3.3 V. Do not feed 5 V signals into GPIO.", beginnerTip:"MicroPython makes it friendly for learners coming from Python.", compatibleBoards:["Raspberry Pi Pico"] },
  { slug:"microbit", name:"BBC micro:bit", category:"Microcontrollers", summary:"An education-focused board with buttons, LEDs, radio and built-in sensors.", voltage:"3 V / 3.3 V logic", interface:"MakeCode / MicroPython / GPIO / radio / Bluetooth", pins:"Large ring pins plus edge connector; board revision changes some built-in hardware.", safety:"Keep external circuits within micro:bit voltage/current limits.", beginnerTip:"Excellent for first projects because many inputs and outputs are already built in.", compatibleBoards:["BBC micro:bit"] },
  { slug:"stm32", name:"STM32 development board", category:"Microcontrollers", summary:"A family of 32-bit microcontroller boards used in embedded systems.", voltage:"Usually 3.3 V logic; exact board varies", interface:"GPIO / ADC / UART / I2C / SPI / timers", pins:"Pin map depends on the exact STM32 board and MCU.", safety:"Confirm the exact board, pinout and voltage before wiring.", beginnerTip:"Best after basic microcontroller concepts are already comfortable.", compatibleBoards:["STM32"] },

  { slug:"breadboard", name:"Solderless breadboard", category:"Prototyping", summary:"A reusable board for building temporary circuits without soldering.", voltage:"Depends on the circuit", interface:"Physical electrical connections", pins:"Rows and power rails are internally connected; some rails are split.", safety:"Disconnect power before moving wires and check rails for accidental shorts.", beginnerTip:"Learn how rows and rails connect before building a powered circuit.", compatibleBoards:allBoards },
  { slug:"jumper-wires", name:"Jumper wires", category:"Prototyping", summary:"Reusable wires for connecting boards, breadboards and modules.", voltage:"Depends on circuit", interface:"Male-male / male-female / female-female", pins:"No fixed pins.", safety:"Do not use damaged wires or force connectors onto the wrong pins.", beginnerTip:"Use consistent wire colours for power, ground and signals.", compatibleBoards:allBoards },

  { slug:"resistor-330", name:"330 Ω resistor", category:"Basic electronics", summary:"A common resistor value for limiting indicator LED current in beginner circuits.", voltage:"Passive component; rating depends on power", interface:"Two-terminal passive", pins:"No polarity.", safety:"Choose a suitable resistance and power rating for the circuit.", beginnerTip:"Often used in series with an LED.", compatibleBoards:allBoards },
  { slug:"resistor-10k", name:"10 kΩ resistor", category:"Basic electronics", summary:"A common value for pull-up, pull-down and sensor divider circuits.", voltage:"Passive component; rating depends on power", interface:"Two-terminal passive", pins:"No polarity.", safety:"Confirm the resistor value before using it in a divider or bias network.", beginnerTip:"Useful for buttons, LDR dividers and defined input states.", compatibleBoards:allBoards },
  { slug:"potentiometer", name:"Potentiometer", category:"Inputs", summary:"A variable resistor commonly used as a knob or adjustable analog input.", voltage:"Use within board analog-input range", interface:"Analog voltage divider", pins:"Two end terminals plus a centre wiper.", safety:"Wire it as a divider before feeding the wiper to an analog input.", beginnerTip:"Great for learning how changing voltage becomes a changing number.", compatibleBoards:allBoards },
  { slug:"led", name:"LED", category:"Basic electronics", summary:"A polarized light-emitting diode used as a simple visual output.", voltage:"Typical forward voltage varies by colour", interface:"Digital output through current limiting", pins:"Anode (+) and cathode (-).", safety:"Always use an appropriate current-limiting resistor.", beginnerTip:"If it does not light, check polarity, resistor and ground.", compatibleBoards:allBoards },
  { slug:"rgb-led", name:"RGB LED", category:"Basic electronics", summary:"Three LEDs in one package for mixing red, green and blue light.", voltage:"Channel forward voltage varies", interface:"Digital or PWM outputs", pins:"Common-anode or common-cathode versions differ.", safety:"Use a resistor for each colour channel and identify the package type first.", beginnerTip:"Test one colour at a time before mixing colours.", compatibleBoards:allBoards },
  { slug:"diode", name:"Diode", category:"Basic electronics", summary:"A component that mainly allows current in one direction.", voltage:"Part-specific", interface:"Two-terminal polarized device", pins:"Anode and cathode; stripe commonly marks cathode.", safety:"Use the correct diode type and orientation for the application.", beginnerTip:"A flyback diode is important when switching inductive loads such as relays or coils.", compatibleBoards:allBoards },
  { slug:"transistor-npn", name:"NPN transistor", category:"Drivers", summary:"A transistor that can let a low-current control signal switch a larger load.", voltage:"Part-specific", interface:"Base / collector / emitter", pins:"Pin order depends on transistor model.", safety:"Use a base resistor and respect voltage/current ratings.", beginnerTip:"Check the datasheet because transistor pin order is not universal.", compatibleBoards:allBoards },
  { slug:"mosfet", name:"Logic-level N-channel MOSFET", category:"Drivers", summary:"An efficient electronic switch for suitable DC loads.", voltage:"Part-specific", interface:"Gate / drain / source", pins:"Pin order depends on MOSFET model.", safety:"Choose a logic-level device appropriate for the load and add protection for inductive loads.", beginnerTip:"Useful for switching higher-current DC loads without loading a GPIO pin.", compatibleBoards:allBoards },
  { slug:"push-button", name:"Push button", category:"Inputs", summary:"A momentary switch used for digital user input.", voltage:"Use within logic voltage", interface:"Digital input", pins:"Many tactile switches have paired internal contacts.", safety:"Do not wire the switch so pressing it shorts power to ground.", beginnerTip:"Use INPUT_PULLUP or a pull resistor to avoid a floating input.", compatibleBoards:allBoards },
  { slug:"toggle-switch", name:"Toggle / slide switch", category:"Inputs", summary:"A maintained switch that stays in its selected position.", voltage:"Switch rating and circuit dependent", interface:"Digital input or low-current power control", pins:"SPST/SPDT layouts vary.", safety:"Do not use a small signal switch for loads above its rating.", beginnerTip:"Great for simple mode selection or battery on/off.", compatibleBoards:allBoards },
  { slug:"rotary-encoder", name:"Rotary encoder", category:"Inputs", summary:"A rotating input that reports direction and steps; many also include a push switch.", voltage:"Module dependent", interface:"Digital pulse inputs", pins:"Common module labels include CLK, DT, SW, VCC, GND.", safety:"Confirm module voltage and pull-up requirements.", beginnerTip:"Use it for menu navigation or adjustable values.", compatibleBoards:allBoards },
  { slug:"joystick", name:"Analog joystick module", category:"Inputs", summary:"A two-axis analog input with an optional push switch.", voltage:"Module dependent; keep outputs within ADC limits", interface:"Two analog axes + digital switch", pins:"Common labels: VRx, VRy, SW, VCC, GND.", safety:"Do not exceed the selected board's analog-input voltage.", beginnerTip:"Read one axis first, then add the second and the switch.", compatibleBoards:allBoards },
  { slug:"keypad-4x4", name:"4×4 matrix keypad", category:"Inputs", summary:"A 16-key keypad scanned using row and column lines.", voltage:"Logic voltage", interface:"Digital matrix", pins:"Eight row/column connections; order varies by keypad.", safety:"Identify row/column order before wiring.", beginnerTip:"Useful for PIN entry and menu controls.", compatibleBoards:allBoards },

  { slug:"ldr", name:"Photoresistor (LDR)", category:"Sensors", summary:"A light-sensitive resistor used in an analog voltage divider.", voltage:"Use divider output within ADC limits", interface:"Analog", pins:"Two non-polarized leads.", safety:"Do not feed a divider voltage above the board ADC range.", beginnerTip:"Pair it with a 10 kΩ resistor and watch readings change with light.", compatibleBoards:allBoards },
  { slug:"dht11-dht22", name:"DHT11 / DHT22", category:"Sensors", summary:"Digital sensors for classroom temperature and relative-humidity measurements.", voltage:"Sensor/module dependent", interface:"Single-wire-style digital protocol", pins:"Bare sensors and modules may have different pin order; confirm the exact part.", safety:"Verify VCC, DATA and GND before power. Do not guess pin order.", beginnerTip:"If readings are NaN, check power, ground, data pin and configured sensor type.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"ds18b20", name:"DS18B20 temperature sensor", category:"Sensors", summary:"A digital temperature sensor commonly used with the 1-Wire protocol.", voltage:"Part/module dependent", interface:"1-Wire", pins:"Common bare package pins: GND, DATA, VDD; verify orientation.", safety:"Check package orientation and use the recommended pull-up resistor.", beginnerTip:"Good for learning how several digital sensors can share one bus.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"lm35", name:"LM35 temperature sensor", category:"Sensors", summary:"An analog temperature sensor that outputs a voltage related to temperature.", voltage:"Part-specific", interface:"Analog", pins:"Package orientation matters; verify datasheet.", safety:"Keep output within the board ADC range.", beginnerTip:"Useful for learning voltage-to-measurement conversion.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"hc-sr04", name:"HC-SR04 ultrasonic sensor", category:"Sensors", summary:"Measures distance by timing an ultrasonic pulse echo.", voltage:"Common modules use 5 V", interface:"TRIG + ECHO digital timing", pins:"VCC, TRIG, ECHO, GND.", safety:"ECHO is commonly a 5 V signal. Protect 3.3 V GPIO with suitable level shifting/division.", beginnerTip:"First print distance values before connecting motors or alarms.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"pir", name:"PIR motion sensor", category:"Sensors", summary:"Detects changes in infrared radiation associated with movement.", voltage:"Module dependent", interface:"Digital output", pins:"Common modules expose VCC, OUT, GND.", safety:"Confirm supply and output levels for the exact module.", beginnerTip:"Allow the module time to stabilise after power-up.", compatibleBoards:allBoards },
  { slug:"ir-obstacle", name:"IR obstacle sensor", category:"Sensors", summary:"An infrared reflection module often used for short-range object detection.", voltage:"Module dependent", interface:"Usually digital, sometimes analog", pins:"Common labels: VCC, GND, OUT.", safety:"Confirm output voltage before connecting to 3.3 V GPIO.", beginnerTip:"Ambient light and surface colour can change detection reliability.", compatibleBoards:allBoards },
  { slug:"line-sensor", name:"Line-tracking sensor", category:"Sensors", summary:"An optical reflectance sensor used to distinguish dark and light surfaces.", voltage:"Module dependent", interface:"Digital or analog", pins:"Module-specific.", safety:"Confirm output voltage for the selected board.", beginnerTip:"Calibrate over the actual track surface before running the robot.", compatibleBoards:allBoards },
  { slug:"soil-moisture", name:"Soil-moisture sensor", category:"Sensors", summary:"Measures a proxy for soil moisture for plant-monitoring experiments.", voltage:"Module dependent", interface:"Analog and/or digital", pins:"Module-specific.", safety:"Simple resistive probes can corrode and readings are not precision water measurements.", beginnerTip:"Treat readings as relative values and calibrate with your own soil.", compatibleBoards:allBoards },
  { slug:"water-level", name:"Water-level sensor", category:"Sensors", summary:"A simple module for detecting or estimating contact with water.", voltage:"Module dependent", interface:"Analog or digital", pins:"Module-specific.", safety:"Keep electronics and exposed power connections safely away from spills.", beginnerTip:"Use only for supervised low-voltage experiments.", compatibleBoards:allBoards },
  { slug:"rain-sensor", name:"Rain sensor module", category:"Sensors", summary:"A wetness-detection board used for simple rain/contact experiments.", voltage:"Module dependent", interface:"Analog and/or digital", pins:"Module-specific.", safety:"Keep the comparator/control board dry unless it is specifically designed for exposure.", beginnerTip:"Use it to compare dry and wet readings rather than as a calibrated weather instrument.", compatibleBoards:allBoards },
  { slug:"mpu6050", name:"MPU6050 accelerometer + gyroscope", category:"Sensors", summary:"A six-axis motion sensor for measuring acceleration and rotation.", voltage:"Common breakout modules vary; logic is typically 3.3 V", interface:"I2C", pins:"Common labels include VCC, GND, SCL, SDA, INT.", safety:"Confirm breakout-board voltage support before powering.", beginnerTip:"Start by reading raw acceleration and gyro values before using advanced fusion.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"bme280", name:"BME280 environmental sensor", category:"Sensors", summary:"Measures temperature, humidity and air pressure on common breakout boards.", voltage:"Breakout dependent; sensor is 3.3 V", interface:"I2C or SPI", pins:"Common breakout labels include VIN/3V3, GND, SCL/SCK, SDA/SDI.", safety:"Verify whether the breakout includes a regulator/level shifting before applying 5 V.", beginnerTip:"I2C mode uses fewer wires and is a good starting point.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"gas-sensor", name:"MQ-series gas/smoke sensor module", category:"Sensors", summary:"A heated gas-sensitive module useful for supervised learning experiments.", voltage:"Common modules often use 5 V and draw notable heater current", interface:"Analog and/or digital", pins:"Module-specific.", safety:"Not a certified life-safety detector. Allow for heater current and warm-up.", beginnerTip:"Use it to learn relative sensor response, not to make safety claims.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"flame-sensor", name:"Flame / infrared sensor module", category:"Sensors", summary:"A light-sensitive module that can respond to flame-like infrared sources.", voltage:"Module dependent", interface:"Analog and/or digital", pins:"Module-specific.", safety:"Never create an open flame for unsupervised testing. It is not a certified fire detector.", beginnerTip:"Use safe instructor-approved light sources or demonstrations.", compatibleBoards:allBoards },
  { slug:"hall-sensor", name:"Hall-effect sensor", category:"Sensors", summary:"Detects magnetic fields and can be used for position or wheel-rotation experiments.", voltage:"Part/module dependent", interface:"Digital or analog", pins:"Part-specific.", safety:"Check pinout and voltage before connection.", beginnerTip:"Move a magnet near the sensor and watch the signal change.", compatibleBoards:allBoards },
  { slug:"sound-sensor", name:"Sound sensor module", category:"Sensors", summary:"A microphone-based module for detecting relative sound level or threshold events.", voltage:"Module dependent", interface:"Analog and/or digital", pins:"Module-specific.", safety:"Do not treat it as a calibrated sound-level meter unless appropriately calibrated.", beginnerTip:"Use claps or taps to explore threshold detection.", compatibleBoards:allBoards },

  { slug:"buzzer", name:"Piezo buzzer", category:"Actuators", summary:"Produces simple beeps or tones for alerts and feedback.", voltage:"Part/module dependent", interface:"Digital or PWM/tone", pins:"Polarity may matter on some buzzers.", safety:"Do not drive higher-current sounders directly from GPIO and keep volume reasonable.", beginnerTip:"Identify whether the buzzer is active or passive.", compatibleBoards:allBoards },
  { slug:"vibration-motor", name:"Vibration motor", category:"Actuators", summary:"A small motor that produces haptic vibration feedback.", voltage:"Motor dependent", interface:"Use a transistor/MOSFET driver rather than direct GPIO", pins:"Two motor leads; polarity changes rotation but vibration effect may be similar.", safety:"Do not power the motor directly from GPIO. Use a suitable driver and flyback protection where appropriate.", beginnerTip:"Test short vibration pulses through a driver before using it in a wearable prototype.", compatibleBoards:allBoards },
  { slug:"servo", name:"Micro servo motor", category:"Actuators", summary:"Moves to a commanded angle using a pulse-control signal.", voltage:"Servo dependent, often separate 5 V-class supply", interface:"PWM-style control signal", pins:"Typically power, ground and signal.", safety:"Do not power a loaded servo from a weak GPIO/USB rail. Share ground between supplies.", beginnerTip:"Test movement with no mechanical load first.", compatibleBoards:allBoards },
  { slug:"dc-motor", name:"DC geared motor", category:"Actuators", summary:"A small motor used for robot wheels and other moving mechanisms.", voltage:"Motor dependent", interface:"Requires driver for direction/control", pins:"Two motor terminals.", safety:"Never power a DC motor directly from GPIO.", beginnerTip:"Test one motor through a driver before building a complete robot.", compatibleBoards:allBoards },
  { slug:"stepper-motor", name:"Stepper motor", category:"Actuators", summary:"A motor that moves in discrete steps for controlled positioning.", voltage:"Motor/driver dependent", interface:"Requires stepper driver", pins:"Coil connections depend on motor type.", safety:"Use a correctly matched driver and power supply.", beginnerTip:"Identify coil pairs before connecting the driver.", compatibleBoards:allBoards },
  { slug:"solenoid", name:"Solenoid", category:"Actuators", summary:"An electromagnetic actuator that creates linear motion when energised.", voltage:"Device dependent", interface:"Requires transistor/MOSFET/driver", pins:"Two power leads.", safety:"Use a flyback diode and never drive it directly from GPIO.", beginnerTip:"Start with brief supervised activation to check current and heating.", compatibleBoards:allBoards },

  { slug:"l298n", name:"L298N motor driver", category:"Drivers", summary:"A dual H-bridge module commonly used to control two small DC motors.", voltage:"Motor supply and logic requirements depend on module configuration", interface:"Digital direction + enable/PWM", pins:"IN1–IN4, ENA/ENB, motor outputs, supply and GND.", safety:"Use a suitable motor supply, common ground, and never route motor current through MCU GPIO.", beginnerTip:"Test each motor channel independently before combining them.", compatibleBoards:allBoards },
  { slug:"l293d", name:"L293D motor driver", category:"Drivers", summary:"A dual H-bridge IC for small DC motors.", voltage:"Logic/motor supplies per datasheet", interface:"Digital direction + enable", pins:"IC pinout; use datasheet.", safety:"Observe current limits and use proper motor supply decoupling.", beginnerTip:"Good for understanding the H-bridge concept.", compatibleBoards:allBoards },
  { slug:"tb6612fng", name:"TB6612FNG motor driver", category:"Drivers", summary:"An efficient dual DC-motor driver used in compact robot builds.", voltage:"Module/device dependent", interface:"Direction + PWM", pins:"Common module labels include AIN/BIN, PWMA/PWMB, STBY, VM, VCC, GND.", safety:"Confirm logic and motor supply ranges for the exact breakout.", beginnerTip:"Remember to enable STBY on common breakouts.", compatibleBoards:allBoards },
  { slug:"relay-module", name:"Relay module", category:"Drivers", summary:"An electrically controlled switch module used to isolate/control another circuit.", voltage:"Module and switched load dependent", interface:"Digital control", pins:"Control side plus COM/NO/NC contacts.", safety:"STEMBuild beginner activities should remain low-voltage DC. Do not use mains wiring in learner projects.", beginnerTip:"Practise by switching a safe low-voltage load.", compatibleBoards:allBoards },
  { slug:"uln2003", name:"ULN2003 driver board", category:"Drivers", summary:"A transistor-array driver often paired with small 28BYJ-48 stepper motors.", voltage:"Module/load dependent", interface:"Digital inputs", pins:"IN1–IN4 and motor connector on common boards.", safety:"Use the correct motor supply and common ground as required.", beginnerTip:"Useful for a first stepper-motor project.", compatibleBoards:allBoards },

  { slug:"lcd-1602", name:"16×2 LCD", category:"Displays", summary:"A character display for showing text and sensor values.", voltage:"Module dependent", interface:"Parallel or I2C backpack", pins:"Parallel and I2C versions differ.", safety:"Confirm display/backpack voltage and contrast wiring.", beginnerTip:"An I2C backpack reduces the number of wires.", compatibleBoards:allBoards },
  { slug:"oled-i2c", name:"I2C OLED display", category:"Displays", summary:"A small high-contrast display for text, icons and simple graphs.", voltage:"Breakout dependent", interface:"I2C", pins:"Common labels: VCC, GND, SCL, SDA.", safety:"Verify breakout voltage support before powering.", beginnerTip:"Run an I2C scanner if the display is not found.", compatibleBoards:allBoards },
  { slug:"seven-segment", name:"7-segment display", category:"Displays", summary:"A numeric LED display used for counters and timers.", voltage:"LED segment dependent", interface:"Digital outputs or driver IC", pins:"Common-anode and common-cathode types differ.", safety:"Use current-limiting resistors or an appropriate driver.", beginnerTip:"Start by lighting one segment before displaying numbers.", compatibleBoards:allBoards },
  { slug:"led-matrix", name:"LED matrix", category:"Displays", summary:"A grid of LEDs for patterns, characters and simple animations.", voltage:"Module dependent", interface:"Direct matrix or driver such as MAX7219", pins:"Module-specific.", safety:"Use appropriate current limiting/driver hardware.", beginnerTip:"A driver module makes first projects much easier.", compatibleBoards:allBoards },
  { slug:"tft-display", name:"TFT display", category:"Displays", summary:"A colour graphical display for richer user interfaces.", voltage:"Module dependent", interface:"Often SPI", pins:"Module-specific.", safety:"Confirm logic voltage and power requirements.", beginnerTip:"Begin with a known library example for your exact controller chip.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },

  { slug:"hc05", name:"HC-05 Bluetooth module", category:"Communication", summary:"A classic Bluetooth serial module used for simple wireless control.", voltage:"Module power and RX logic require care; many breakout RX inputs should be protected from 5 V logic", interface:"UART serial", pins:"Common labels: VCC, GND, TXD, RXD, EN/KEY, STATE.", safety:"Protect module RX if your controller transmits 5 V logic and verify breakout specifications.", beginnerTip:"Test serial messages before connecting motors.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"nrf24l01", name:"nRF24L01 radio module", category:"Communication", summary:"A 2.4 GHz digital radio module for board-to-board communication.", voltage:"3.3 V", interface:"SPI", pins:"VCC, GND, CE, CSN, SCK, MOSI, MISO, IRQ.", safety:"Do not power the module from 5 V. Use stable 3.3 V power and local decoupling.", beginnerTip:"First send a simple counter between two boards.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"lora", name:"LoRa radio module", category:"Communication", summary:"A long-range low-data-rate radio module used for telemetry experiments.", voltage:"Module-specific, often 3.3 V logic", interface:"Usually SPI or UART", pins:"Module-specific.", safety:"Use legal regional frequency bands and a suitable antenna; never transmit without following module requirements.", beginnerTip:"Begin with short packets such as sensor readings.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"sim800", name:"SIM800 / SIM800C GSM module", category:"Communication", summary:"A cellular module for SMS, calls and low-rate data on supported 2G networks.", voltage:"Requires a robust module-appropriate supply with high current peaks", interface:"UART + SIM/network", pins:"Module-specific power, UART and control pins.", safety:"Do not power it from a weak MCU 5 V pin. Confirm local network compatibility and SIM requirements.", beginnerTip:"Get stable power and basic AT-command responses before writing application logic.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"neo6m", name:"NEO-6M / NEO-M8N GPS module", category:"Communication", summary:"A satellite-positioning receiver module for location and time data.", voltage:"Breakout dependent", interface:"UART serial", pins:"Common labels: VCC, GND, TX, RX.", safety:"Verify breakout voltage and allow clear sky view for testing.", beginnerTip:"First print raw NMEA data, then parse latitude/longitude.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"rfid-rc522", name:"MFRC522 RFID module", category:"Communication", summary:"A short-range RFID/NFC reader commonly used with 13.56 MHz cards/tags.", voltage:"3.3 V", interface:"SPI", pins:"SDA/SS, SCK, MOSI, MISO, IRQ, GND, RST, 3.3 V on common boards.", safety:"Do not power the module from 5 V.", beginnerTip:"Start by reading a card UID, not by building an access-control system.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"sd-card", name:"MicroSD card module", category:"Communication", summary:"Stores logs, sensor readings and files on a microSD card.", voltage:"Module dependent; card logic is 3.3 V", interface:"SPI", pins:"Common labels: CS, SCK, MOSI, MISO, VCC, GND.", safety:"Verify level shifting and supply support on the exact module.", beginnerTip:"Start by creating and reading one small text file.", compatibleBoards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"] },
  { slug:"rtc", name:"RTC clock module", category:"Communication", summary:"Keeps date and time for logging and scheduled actions.", voltage:"Module dependent", interface:"Usually I2C", pins:"Common labels: VCC, GND, SDA, SCL.", safety:"Use the correct backup battery type for the module.", beginnerTip:"Read the clock first, then add timestamps to sensor data.", compatibleBoards:allBoards },

  { slug:"battery-pack", name:"Battery pack", category:"Power", summary:"A portable low-voltage supply for robots and embedded projects.", voltage:"Depends on cell count and chemistry", interface:"Power", pins:"Positive and negative output.", safety:"Use a pack appropriate for the load, polarity and board voltage. Never short the terminals.", beginnerTip:"Measure the pack voltage before connecting it.", compatibleBoards:allBoards },
  { slug:"18650", name:"18650 Li-ion cell", category:"Power", summary:"A rechargeable lithium-ion cell used in many portable projects.", voltage:"Typically 3.6/3.7 V nominal per cell", interface:"Battery power", pins:"Positive and negative cell terminals.", safety:"Use protected cells and a proper charger/BMS. Never short, puncture or charge with an unsuitable circuit.", beginnerTip:"Use only with instructor-approved holders and charging hardware.", compatibleBoards:allBoards },
  { slug:"tp4056", name:"TP4056 Li-ion charger module", category:"Power", summary:"A charger module commonly used for a single Li-ion cell.", voltage:"Single-cell Li-ion charging; module-specific input", interface:"Power management", pins:"Common boards expose IN+/IN-, B+/B-, OUT+/OUT- depending on version.", safety:"Use only with suitable single-cell Li-ion batteries and understand whether the module includes protection.", beginnerTip:"Power design should be teacher-reviewed before a learner relies on it unattended.", compatibleBoards:allBoards },
  { slug:"buck-converter", name:"Buck converter", category:"Power", summary:"A DC-DC converter that reduces a higher DC voltage to a lower regulated voltage.", voltage:"Module-specific input/output range", interface:"Power conversion", pins:"VIN+/VIN-, VOUT+/VOUT-.", safety:"Set and measure the output before connecting electronics.", beginnerTip:"Adjust with no sensitive board attached, then confirm with a multimeter.", compatibleBoards:allBoards },
  { slug:"boost-converter", name:"Boost converter", category:"Power", summary:"A DC-DC converter that raises a lower DC voltage to a higher voltage.", voltage:"Module-specific", interface:"Power conversion", pins:"VIN+/VIN-, VOUT+/VOUT-.", safety:"Confirm output voltage before connecting a load and stay within current/power ratings.", beginnerTip:"Remember that raising voltage does not create free power.", compatibleBoards:allBoards },
  { slug:"solar-panel", name:"Small solar panel", category:"Power", summary:"A low-voltage photovoltaic panel for energy-harvesting experiments.", voltage:"Panel-specific and sunlight-dependent", interface:"Power source", pins:"Positive and negative leads.", safety:"Use a suitable charge controller/regulator between the panel and rechargeable batteries/electronics.", beginnerTip:"Measure open-circuit voltage and loaded voltage to see how sunlight changes output.", compatibleBoards:allBoards },

  { slug:"robot-chassis", name:"Robot chassis", category:"Mechanical", summary:"A frame for mounting a controller, motors, sensors and battery.", voltage:"Not applicable", interface:"Mechanical", pins:"None.", safety:"Secure loose wires away from wheels and moving parts.", beginnerTip:"Mount the heavy battery low and keep sensor views unobstructed.", compatibleBoards:allBoards },
  { slug:"robot-wheels", name:"Robot wheels + caster", category:"Mechanical", summary:"Wheels and a support caster for a small mobile robot.", voltage:"Not applicable", interface:"Mechanical", pins:"None.", safety:"Lift wheels off the floor for first motor tests.", beginnerTip:"Check that both driven wheels rotate freely before debugging code.", compatibleBoards:allBoards },
  { slug:"servo-bracket", name:"Servo / sensor mounting bracket", category:"Mechanical", summary:"A bracket for securely mounting a servo or sensor.", voltage:"Not applicable", interface:"Mechanical", pins:"None.", safety:"Keep fingers and cables clear of moving parts.", beginnerTip:"Do not overtighten small plastic servo horns.", compatibleBoards:allBoards },
];

export const buildProjects: BuildProject[] = [
  { slug:"first-led", title:"My First LED Circuit", level:"Beginner", area:"Electronics", summary:"Learn polarity, current limiting and your first digital output.", outcome:"An LED turns on safely and then blinks from code.", minutes:30, boards:allBoards, required:["breadboard","jumper-wires","led","resistor-330"], skills:["Polarity","Breadboard wiring","Digital output"], firstTest:"Power off, inspect the resistor and LED polarity, then run a simple blink.", troubleshoot:["LED reversed","Wrong GPIO","Missing ground","Resistor not in series"], improve:["Add a second LED","Create a traffic-light pattern","Control brightness with PWM"] },
  { slug:"traffic-light", title:"Traffic Light", level:"Beginner", area:"Electronics", summary:"Use three LEDs to create a timed sequence.", outcome:"Red, amber and green lights follow a repeatable sequence.", minutes:45, boards:allBoards, required:["breadboard","jumper-wires","led","resistor-330"], optional:["rgb-led"], skills:["Sequencing","Digital outputs","Timing"], firstTest:"Test each LED separately before running the full sequence.", troubleshoot:["One LED never lights","Pins in code do not match wiring","Common ground missing"], improve:["Add a pedestrian button","Add a buzzer","Create night mode"] },
  { slug:"button-light", title:"Push-Button Light", level:"Beginner", area:"Programming", summary:"Use a button to control an LED and learn digital input.", outcome:"Pressing the button changes the LED predictably.", minutes:40, boards:allBoards, required:["breadboard","jumper-wires","push-button","led","resistor-330"], optional:["resistor-10k"], skills:["Digital input","Pull resistors","Conditional logic"], firstTest:"Print the button state before controlling the LED.", troubleshoot:["Floating input","Button orientation","INPUT_PULLUP logic reversed"], improve:["Toggle the LED","Add debounce","Count button presses"] },
  { slug:"light-detector", title:"Automatic Light Detector", level:"Beginner", area:"Sensors", summary:"Measure light and turn on an indicator when it becomes dark.", outcome:"Sensor readings change with light and an LED responds to a chosen threshold.", minutes:50, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["breadboard","jumper-wires","ldr","resistor-10k","led","resistor-330"], skills:["Analog input","Voltage divider","Thresholds"], firstTest:"Print the raw LDR reading and cover/uncover the sensor.", troubleshoot:["Divider wired incorrectly","ADC pin wrong","Threshold does not match actual readings"], improve:["Add a potentiometer threshold","Show values on OLED","Log readings"] },
  { slug:"reaction-game", title:"Reaction Timer Game", level:"Beginner", area:"Programming", summary:"Use an LED, button and timing code to make a simple game.", outcome:"The game measures how quickly the learner presses after the signal.", minutes:60, boards:allBoards, required:["breadboard","jumper-wires","led","resistor-330","push-button"], optional:["buzzer"], skills:["Timing","Random delay","Inputs and outputs"], firstTest:"Confirm button and LED independently before measuring reaction time.", troubleshoot:["Button bounce","Timer starts at wrong moment","Serial output missing"], improve:["Add best score","Add sound","Two-player mode"] },
  { slug:"door-alarm", title:"Mini Door / Motion Alarm", level:"Beginner", area:"Sensors", summary:"Detect movement and give a simple low-voltage alert.", outcome:"A motion event triggers an LED/buzzer alert.", minutes:50, boards:allBoards, required:["jumper-wires","pir","buzzer"], optional:["led","resistor-330"], skills:["Digital sensors","State changes","Alerts"], firstTest:"Print the PIR output and wait for the sensor to stabilise.", troubleshoot:["PIR warm-up","False triggers","Wrong signal voltage"], improve:["Add arming delay","Add display","Log event times"] },
  { slug:"temperature-display", title:"Temperature Display", level:"Beginner", area:"Sensors", summary:"Read temperature and show or print the measurement.", outcome:"Real sensor readings appear with correct units.", minutes:55, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["breadboard","jumper-wires","ds18b20"], optional:["lcd-1602","oled-i2c"], skills:["Digital sensor reading","Units","Validation"], firstTest:"Print one valid temperature reading before adding a display.", troubleshoot:["Sensor pinout","Missing pull-up","Library/config mismatch"], improve:["Add min/max","Add an alert threshold","Log readings"] },
  { slug:"electronic-dice", title:"Electronic Dice", level:"Beginner", area:"Programming", summary:"Generate a random value and show it with LEDs or a display.", outcome:"A button press produces values from 1 to 6.", minutes:60, boards:allBoards, required:["push-button","led","resistor-330","breadboard","jumper-wires"], optional:["seven-segment"], skills:["Random numbers","Arrays","User input"], firstTest:"Print random values first, then map them to outputs.", troubleshoot:["Same value repeated unexpectedly","Button bounce","LED mapping wrong"], improve:["Use a 7-segment display","Add animation","Track rolls"] },

  { slug:"smart-environment-monitor", title:"Smart Environment Monitor", level:"Intermediate", area:"IoT", summary:"Measure temperature and humidity, interpret readings and document evidence.", outcome:"Validated readings are recorded and status indicators respond to classroom thresholds.", minutes:90, boards:["Arduino Uno","ESP32"], required:["breadboard","jumper-wires","dht11-dht22","led","resistor-330"], optional:["buzzer","oled-i2c"], skills:["Sensor integration","Data validation","Evidence","Troubleshooting"], firstTest:"Get stable temperature/humidity readings before adding indicators.", troubleshoot:["NaN reading","Wrong DHT type","Wrong data pin","Power/ground issue"], improve:["Add OLED","Log readings","ESP32 dashboard extension"] },
  { slug:"plant-monitor", title:"Smart Plant Monitor", level:"Intermediate", area:"IoT", summary:"Measure soil moisture and create a simple plant-status indicator.", outcome:"The learner calibrates dry/wet values and reports plant-soil status.", minutes:75, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["soil-moisture","led","resistor-330","jumper-wires"], optional:["oled-i2c","buzzer"], skills:["Calibration","Analog sensing","Thresholds"], firstTest:"Record dry and moist reference readings before deciding a threshold.", troubleshoot:["Corroded/dirty probe","Unstable analog reading","Threshold copied instead of calibrated"], improve:["Add OLED","Add data logging","Use a more durable capacitive probe"] },
  { slug:"smart-dustbin", title:"Smart Dustbin", level:"Intermediate", area:"Robotics", summary:"Detect an approaching object and move a lid with a servo.", outcome:"The lid opens only when the distance condition is met.", minutes:90, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["hc-sr04","servo","jumper-wires"], optional:["servo-bracket"], skills:["Distance sensing","Servo control","State logic"], firstTest:"Read distance first, then test servo separately with no load.", troubleshoot:["5 V echo into 3.3 V board","Servo power resets MCU","Noisy distance"], improve:["Add close delay","Add status light","Add fill-level sensing"] },
  { slug:"parking-assistant", title:"Parking Distance Assistant", level:"Intermediate", area:"Sensors", summary:"Use distance to control visual and audible proximity feedback.", outcome:"Indicators change as an object moves closer.", minutes:75, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["hc-sr04","led","resistor-330","buzzer","jumper-wires"], skills:["Distance measurement","Mapping","Alerts"], firstTest:"Print distance values before adding the buzzer pattern.", troubleshoot:["Echo voltage","Timeout handling","Bad sensor angle"], improve:["Add OLED distance","Use multiple LEDs","Add smoothing"] },
  { slug:"room-light", title:"Automatic Room Light", level:"Intermediate", area:"Sensors", summary:"Combine light and motion sensing to decide when a light indicator should turn on.", outcome:"The output follows a clear light + motion rule.", minutes:80, boards:allBoards, required:["ldr","resistor-10k","pir","led","resistor-330","jumper-wires"], skills:["Multiple sensors","Boolean logic","Energy-awareness"], firstTest:"Test each sensor separately before combining conditions.", troubleshoot:["Conflicting thresholds","PIR warm-up","ADC range"], improve:["Add timeout","Add manual override","Log activation time"] },
  { slug:"water-level-monitor", title:"Water Level Monitor", level:"Intermediate", area:"Sensors", summary:"Detect changing water contact/level in a supervised low-voltage setup.", outcome:"The learner records sensor changes and drives status indicators.", minutes:75, boards:allBoards, required:["water-level","led","resistor-330","jumper-wires"], optional:["buzzer"], skills:["Analog/digital sensing","Safety","Calibration"], firstTest:"Keep the control electronics dry and test the sensor with small controlled changes.", troubleshoot:["Wet electronics","Corrosion","Threshold mismatch"], improve:["Add multiple level states","Add display","Create a tank-status dashboard"] },
  { slug:"bluetooth-car", title:"Bluetooth-Controlled Car", level:"Intermediate", area:"Robotics", summary:"Drive a two-motor robot using wireless serial commands.", outcome:"F/B/L/R/S commands control movement predictably and fail safe to stop.", minutes:120, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["robot-chassis","robot-wheels","dc-motor","l298n","battery-pack","jumper-wires","hc05"], skills:["Motor driver","UART/Bluetooth","Command handling","Fail-safe stop"], firstTest:"Test F/B/L/R/S in serial output before letting the wheels touch the floor.", troubleshoot:["Motor supply","Common ground","RX/TX wiring","Motor polarity"], improve:["Add speed control","Add obstacle stop","Add headlights"] },
  { slug:"obstacle-robot", title:"Obstacle-Avoiding Robot", level:"Intermediate", area:"Robotics", summary:"Combine distance sensing and motor control to make an autonomous robot.", outcome:"The robot moves, stops for nearby obstacles and changes direction.", minutes:150, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["robot-chassis","robot-wheels","dc-motor","l298n","hc-sr04","battery-pack","jumper-wires"], skills:["Robotics integration","Distance sensing","Motor control","Debugging"], firstTest:"Lift the wheels and test motors and distance sensor separately.", troubleshoot:["Motor polarity","Echo voltage","MCU resets","Traction","Sensor timeout"], improve:["Add servo scanning","Choose clearer direction","Add Bluetooth override"] },
  { slug:"line-follower", title:"Line-Following Robot", level:"Intermediate", area:"Robotics", summary:"Use reflectance sensors to steer a robot along a track.", outcome:"The robot follows a prepared dark/light path at a controlled speed.", minutes:150, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["robot-chassis","robot-wheels","dc-motor","l298n","line-sensor","battery-pack","jumper-wires"], skills:["Calibration","Feedback control","Motor steering"], firstTest:"Calibrate sensor readings over both track colours before moving.", troubleshoot:["Sensor height","Track contrast","Motor mismatch","Speed too high"], improve:["Add PID-style control","Count laps","Add intersections"] },
  { slug:"weather-station", title:"Mini Weather Station", level:"Intermediate", area:"IoT", summary:"Combine environmental sensing, display and optional logging.", outcome:"Temperature, humidity and pressure are shown with timestamps or logs.", minutes:120, boards:["Arduino Uno","Arduino Nano","ESP32","Raspberry Pi Pico","STM32"], required:["bme280","oled-i2c","jumper-wires"], optional:["rtc","sd-card"], skills:["I2C","Environmental data","Display","Logging"], firstTest:"Use an I2C scan, then read the BME280 before adding display/logging.", troubleshoot:["Wrong I2C address","Voltage mismatch","Library mismatch"], improve:["Add SD logging","Add ESP32 dashboard","Plot trends"] },

  { slug:"connected-sensor-dashboard", title:"Connected Sensor Dashboard", level:"Advanced", area:"IoT", summary:"Send validated sensor readings from a connected board to an application endpoint.", outcome:"A documented, authenticated telemetry flow is designed and tested with real readings.", minutes:180, boards:["ESP32"], required:["esp32","dht11-dht22"], optional:["oled-i2c","bme280"], skills:["IoT architecture","JSON","Validation","Networking"], firstTest:"Validate sensor data locally before attempting network transmission.", troubleshoot:["Wi-Fi credentials","Invalid payload","Reconnect logic","Rate too high"], improve:["Add device identity","Add charts","Add offline queue"] },
  { slug:"livestock-tracker", title:"Livestock Tracker Prototype", level:"Advanced", area:"IoT", summary:"Combine positioning, communication and power planning into a field-device prototype.", outcome:"The learner demonstrates GPS acquisition and a safe telemetry/prototype plan.", minutes:240, boards:["ESP32","STM32"], required:["neo6m","battery-pack"], optional:["lora","sim800","solar-panel","18650"], skills:["GPS","Telemetry","Power budget","Field design"], firstTest:"Obtain and print valid GPS data before adding communication.", troubleshoot:["No satellite fix","Insufficient power","Antenna placement","UART settings"], improve:["Add geofencing","Add solar charging design","Add low-power mode"] },
  { slug:"assistive-distance-aid", title:"Assistive Distance-Awareness Prototype", level:"Advanced", area:"Robotics", summary:"Explore how sensing and feedback can support an assistive-device concept.", outcome:"A supervised prototype reports nearby obstacles through safe feedback without claiming medical reliability.", minutes:180, boards:["Arduino Uno","ESP32","Raspberry Pi Pico","STM32"], required:["hc-sr04","buzzer","battery-pack"], optional:["mpu6050","vibration-motor"], skills:["Assistive design","Human factors","Sensing","Safety"], firstTest:"Validate distance sensing on a bench before any wearable or mobility trial.", troubleshoot:["False readings","Feedback too frequent","Unsafe mounting"], improve:["Add haptic feedback","Use multiple sensors","Co-design with users"] },
];

export const componentCategories: ComponentCategory[] = [
  "Microcontrollers","Prototyping","Basic electronics","Inputs","Sensors","Displays","Actuators","Drivers","Communication","Power","Mechanical"
];

export function componentBySlug(slug: string) {
  return componentCatalog.find((item) => item.slug === slug);
}

export function projectBySlug(slug: string) {
  return buildProjects.find((item) => item.slug === slug);
}

export function projectsUsingComponent(slug: string) {
  return buildProjects.filter((project) => project.required.includes(slug) || project.optional?.includes(slug));
}
