import type { Metadata } from "next";
import Link from "next/link";
import { PublicHeader } from "@/components/public-header";
import { PublicFooter } from "@/components/public-footer";

export const metadata: Metadata = { title: "Teacher setup guide", description: "Set up a STEMBuild class, assign practical lessons, review evidence and support learners using shared hardware." };

export default function TeacherGuide() {
  const steps = [
    ["Prepare accounts and content", "A STEMBuild administrator creates school, teacher and learner accounts, publishes the course and lesson, and configures its board variants and rubric. Ask for account access before the first session; public self-registration is not available."],
    ["Create your class", "Sign in as a teacher, open Classes and assignments and create a class. Add existing learners from your school by email. A join code identifies the class; entering a code alone does not enrol a learner in this MVP."],
    ["Assign the lesson and project", "Open the class, select a published lesson and set an optional due date. Assign the project separately if it is part of your session. Check that the lesson has the board variant your kits need."],
    ["Run the practical session", "Learners sign in with their own accounts, open the assigned lesson, select their board and start the practical task. Inspect wiring before power-up. In shared kits, rotate builder, programmer and recorder roles and assess each learner’s understanding."],
    ["Collect observable evidence", "Learners complete the quiz and submit a circuit/result photo or PDF, code and troubleshooting notes. Evidence files must be 3.5 MB or smaller. A failed build can still provide useful evidence of reasoning; learners should report it honestly."],
    ["Review, give feedback and revisit", "Open Reviews, inspect the evidence and score each rubric criterion. Give written feedback or request revision. Lesson progress combines knowledge checks and practical assessment; opening instructions or receiving an AI response does not prove mastery."],
  ];
  return <><PublicHeader /><main id="main" className="container guide-page"><p className="eyebrow">For teachers &amp; schools</p><h1>A practical session,<br /><span>from setup to feedback.</span></h1><p className="lead">Start with one class, one shared kit and one observable learning goal.</p><div className="actions"><Link className="btn btn-primary" href="/login">Open your workspace</Link><Link className="btn" href="/showcase/smart-environment-monitor">Try the sample lesson</Link></div><section className="section"><h2>Your first classroom session</h2><div className="guide-steps">{steps.map(([title, text], i) => <article className="card" key={title}><p className="eyebrow">Step {i + 1}</p><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="grid grid-2"><article className="card"><h2>When connectivity drops</h2><p>Before the session, learners save their assigned lesson using its offline download control. Confirm it is available in the offline reader on that device.</p><p>Saved lessons and supported activity drafts remain available locally. Reconnect while signed in to sync queued activity. Evidence file uploads and teacher assessments require an online connection.</p><p>On a shared device, switch accounts deliberately. Local drafts belong to the active learner; do not treat unsynchronised notes as submitted evidence.</p></article><article className="card"><h2>Read analytics with context</h2><p>Use repeated attempts, hints, quiz results and rubric scores to decide who needs help with wiring, code or debugging. These signals guide a conversation; they are not a diagnosis.</p><p>A missing record may mean no connection, no opportunity to use the kit or insufficient evidence. Observe the learner’s work before drawing a conclusion.</p><p>AI Lab Coach supports next-step guidance. Teachers remain responsible for safety checks, evidence review and practical assessment.</p></article></section><section className="section card"><h2>Before inviting a class</h2><ul className="list"><li>Confirm teacher and learner sign-in using provisioned accounts.</li><li>Verify the published lesson, board variant, assignment and rubric.</li><li>Test the physical kit and firmware with the exact sensor you will use.</li><li>Agree school consent and data-handling arrangements; minimise personal information in evidence.</li><li>Run one learner submission and teacher review before a full session.</li></ul><Link className="text-link" href="/about">See the pilot and evaluation plan →</Link></section></main><PublicFooter /></>;
}
