import {test,expect} from '@playwright/test';
import {robotMounts} from '../../src/lib/robot-circuit';
test('circuit opens a full laptop workspace, keeps canvas visible and exits without losing projects',async({page})=>{
 await page.setViewportSize({width:1366,height:768});await page.goto('/3d-lab');await page.getByRole('button',{name:'Open full workspace',exact:true}).click();const workspace=page.getByRole('dialog',{name:'STEMBuild full workspace'});await expect(workspace).toBeVisible();
 await workspace.getByLabel('Circuit project',{exact:true}).selectOption('blink');await workspace.getByRole('button',{name:'Load circuit example',exact:true}).click();await workspace.getByRole('button',{name:'Run logic preview',exact:true}).click();await expect(workspace.locator('.cs-output')).toHaveText('LED ON');
 const canvas=await workspace.locator('.cs-canvas-scroll').boundingBox();expect(canvas!.y).toBeGreaterThan(0);expect(canvas!.y+canvas!.height).toBeLessThanOrEqual(768);const controls=await workspace.locator('.cs-test-code').boundingBox();expect(controls!.y+controls!.height).toBeLessThanOrEqual(768);expect(await page.evaluate(()=>document.body.style.overflow)).toBe('hidden');
 await page.screenshot({path:'/tmp/stembuild-circuit-open.png',fullPage:false});await page.keyboard.press('Escape');await expect(workspace).toHaveCount(0);expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden');await expect(page.getByRole('region',{name:'Circuit project studio'})).toContainText('3/3 parts · 3 wires');
});
test('robot selection opens the full workspace with recognisable hardware and a fixed arena',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1366,height:768});await page.goto('/3d-lab');await page.getByRole('tab',{name:/Robot Builder/}).click();const workspace=page.getByRole('dialog',{name:'STEMBuild full workspace'});await expect(workspace).toBeVisible();const arena=page.locator('#robot-arena');
 for(const part of robotMounts){await arena.getByRole('button',{name:part.name,exact:true}).click();await arena.getByRole('button',{name:'Attach selected part',exact:true}).click();}
 await expect(arena).toContainText('7/7 parts correctly mounted');await expect(arena.locator('.robot-assembly image')).toHaveCount(8);const canvas=await arena.locator('.robot-assembly').boundingBox();expect(canvas!.y+canvas!.height).toBeLessThanOrEqual(768);const map=await arena.locator('.robot-map').boundingBox();expect(map!.height).toBeGreaterThan(100);expect(map!.y+map!.height).toBeLessThanOrEqual(768);await expect(arena.getByRole('button',{name:'Start robot',exact:true})).toBeVisible();expect(errors).toEqual([]);await page.screenshot({path:'/tmp/stembuild-robot-open.png',fullPage:false});
});
