import { StatCard } from "@/components/stat-card";
import { getStudentLearningAnalytics } from "@/lib/analytics";
import { db } from "@/lib/db";
import { formatDate, percent, percentRatio } from "@/lib/format";
import { requireRole } from "@/lib/session";

export default async function StudentProgress() {
  const user = await requireRole("STUDENT");
  const [progress, quiz, practical, badges, certificates, analytics] = await Promise.all([
    db.lessonProgress.findMany({ where: { studentId: user.id }, include: { lesson: { include: { module: true } } }, orderBy: { updatedAt: "desc" } }),
    db.quizAttempt.findMany({ where: { studentId: user.id, completedAt: { not: null } }, include: { quiz: { include: { lesson: true } } }, orderBy: { completedAt: "desc" } }),
    db.practicalSubmission.findMany({ where: { studentId: user.id }, include: { task: { include: { lesson: true } }, assessment: true, hardwarePlatform: true }, orderBy: { createdAt: "desc" } }),
    db.studentBadge.findMany({ where: { studentId: user.id }, include: { badge: true }, orderBy: { awardedAt: "desc" } }),
    db.certificate.findMany({ where: { studentId: user.id, status: "ISSUED" }, include: { course: true }, orderBy: { issuedAt: "desc" } }),
    getStudentLearningAnalytics(user.id),
  ]);
  const passedQuiz = quiz.filter((q) => q.passed).length;
  const assessed = practical.filter((p) => p.status === "ASSESSED").length;
  const visibleSkills = analytics.skillMastery.filter((skill) => skill.evidenceCount > 0);

  return <><div className="topbar"><div className="page-title"><div className="eyebrow">Learner progress</div><h1 style={{fontSize:38}}>Knowledge, practical skill and improvement</h1><div className="muted">This dashboard contains only your learning data. Quiz results remain separate from teacher-assessed practical evidence.</div></div></div><div className="grid grid-4"><StatCard label="Lessons completed" value={progress.filter((p) => p.status === "COMPLETED").length}/><StatCard label="Quiz passes" value={`${passedQuiz}/${quiz.length}`}/><StatCard label="Practical assessments" value={assessed}/><StatCard label="Learning events" value={analytics.events.length}/></div>

  <section className="section"><h2>Skill mastery</h2><p className="muted">Practical mastery comes from teacher rubric scores. Knowledge mastery comes from quiz-answer events. A skill stays blank until there is real scored evidence.</p><div className="grid grid-3" style={{marginTop:14}}>{visibleSkills.map((skill) => <div className="card card-muted" key={skill.id}><div className="small muted">{skill.name}</div><div className="metric">{percentRatio(skill.overallMastery)}</div><div className="small muted">Practical {percentRatio(skill.practicalMastery)} · Knowledge {percentRatio(skill.knowledgeMastery)}</div><div className="small muted" style={{marginTop:7}}>{skill.evidenceCount} scored evidence event{skill.evidenceCount === 1 ? "" : "s"}</div></div>)}{visibleSkills.length === 0 ? <div className="card empty">Skill mastery appears after quiz answers or teacher rubric scores are recorded.</div> : null}</div></section>

  <section><h2>Learning pattern</h2><div className="grid grid-4" style={{marginTop:14}}><StatCard label="Quiz attempts" value={analytics.quizAttempts}/><StatCard label="Practical attempts" value={analytics.practicalAttempts}/><StatCard label="Hints requested" value={analytics.hints}/><StatCard label="Troubleshooting records" value={analytics.troubleshooting}/></div><div className="card" style={{marginTop:16}}><div className="eyebrow">Score trend</div><div className="metric">{analytics.trend.label}</div><div className="small muted">{analytics.trend.delta == null ? `At least four scored events are needed; you currently have ${analytics.trend.samples}.` : `Later scored events differ from earlier ones by ${analytics.trend.delta >= 0 ? "+" : ""}${Math.round(analytics.trend.delta * 100)} percentage points.`}</div></div></section>

  <section className="section"><h2>Recent quiz attempts</h2><div className="table-wrap" style={{marginTop:14}}><table><thead><tr><th>Lesson</th><th>Attempt</th><th>Score</th><th>Status</th></tr></thead><tbody>{quiz.map((q) => <tr key={q.id}><td>{q.quiz.lesson.title}</td><td>{q.attemptNo}</td><td>{percent(q.score, q.maxScore)}</td><td><span className={q.passed ? "badge badge-green" : "badge badge-yellow"}>{q.passed ? "Passed" : "Retry"}</span></td></tr>)}</tbody></table></div></section>
  <section><h2>Practical submissions</h2><div className="table-wrap" style={{marginTop:14}}><table><thead><tr><th>Lesson</th><th>Board</th><th>Submission</th><th>Teacher score</th></tr></thead><tbody>{practical.map((p) => <tr key={p.id}><td>{p.task.lesson.title}</td><td>{p.hardwarePlatform.name}</td><td>{p.status.replaceAll("_", " ")}</td><td>{p.assessment ? percent(p.assessment.totalScore, p.assessment.maxScore) : "Awaiting assessment"}</td></tr>)}</tbody></table></div></section>
  <section className="section"><h2>Recent learning events</h2><p className="muted">A compact audit trail of meaningful learning actions—not page views.</p><div className="table-wrap" style={{marginTop:14}}><table><thead><tr><th>Date</th><th>Event</th><th>Context</th><th>Outcome</th></tr></thead><tbody>{analytics.events.slice(0, 20).map((event) => <tr key={event.id}><td>{formatDate(event.occurredAt)}</td><td>{event.type.replaceAll("_", " ").toLowerCase()}</td><td>{event.lesson?.title ?? event.project?.title ?? event.skill?.name ?? "Learning activity"}</td><td>{event.outcome?.replaceAll("_", " ").toLowerCase() ?? "—"}</td></tr>)}{analytics.events.length === 0 ? <tr><td colSpan={4} className="muted">No learning events have been recorded yet.</td></tr> : null}</tbody></table></div></section>
  <section><h2>Earned credentials</h2><div className="grid grid-2" style={{marginTop:14}}>{badges.map((b) => <div className="card" key={b.id}><span className="badge badge-green">Badge</span><h3 style={{marginTop:10}}>{b.badge.title}</h3><p className="muted">{b.badge.description}</p></div>)}{certificates.map((c) => <div className="card" key={c.id}><span className="badge badge-green">Certificate</span><h3 style={{marginTop:10}}>{c.course.title}</h3><div className="small muted">Certificate {c.certificateNumber}</div></div>)}{badges.length === 0 && certificates.length === 0 ? <div className="card empty">Badges and certificates appear only after the required quiz, practical and project assessments are completed.</div> : null}</div></section></>;
}
