import { db } from "@/lib/db";
import { formatDate } from "@/lib/format";
import { requireRole } from "@/lib/session";
import { assessPractical, assessProject } from "@/lib/teacher-actions";

export default async function ReviewsPage(){
 const teacher=await requireRole("TEACHER");
 const [submissions,projects]=await Promise.all([
   db.practicalSubmission.findMany({where:{classroom:{teacherId:teacher.id},status:{in:["SUBMITTED","NEEDS_REVISION"]}},include:{student:true,hardwarePlatform:true,evidence:true,troubleshooting:true,task:{include:{lesson:true,rubric:{include:{criteria:{orderBy:{order:"asc"}}}}}},classroom:true},orderBy:{submittedAt:"asc"}}),
   db.projectSubmission.findMany({where:{status:{in:["SUBMITTED","NEEDS_REVISION"]},classroom:{teacherId:teacher.id}},include:{student:true,hardwarePlatform:true,evidence:true,project:{include:{rubric:{include:{criteria:{orderBy:{order:"asc"}}}}}}},orderBy:{submittedAt:"asc"}}),
 ]);
 return <><div className="topbar"><div className="page-title"><div className="eyebrow">Assessment queue</div><h1 style={{fontSize:38}}>Review practical evidence</h1><div className="muted">Rubric scoring is teacher-owned. AI assistance does not issue the practical grade.</div></div></div><div className="stack">{submissions.map(s=><div className="card" key={s.id}><div className="inline"><span className="badge">Lesson practical</span><span className="badge">{s.classroom?.name}</span><span className="badge">{s.hardwarePlatform.name}</span><span className="badge">Attempt {s.submissionNo}</span><span className="badge">{formatDate(s.submittedAt)}</span></div><h2 style={{fontSize:26,marginTop:12}}>{s.student.displayName} — {s.task.lesson.title}</h2><p className="muted">{s.studentNotes}</p>{s.codeSnippet?<><h3>Submitted code / notes</h3><pre className="code">{s.codeSnippet}</pre></>:null}<div className="inline">{s.evidence.map(e=><a className="btn" href={`/api/evidence/${e.id}`} target="_blank" rel="noreferrer" key={e.id}>Open evidence</a>)}</div>{s.troubleshooting.length?<div style={{marginTop:14}}>{s.troubleshooting.map(t=><p className="small muted" key={t.id}><strong>Issue:</strong> {t.issue}<br/><strong>Tried:</strong> {t.actionTried}<br/><strong>Result:</strong> {t.result}</p>)}</div>:<p className="small muted">No troubleshooting record was submitted.</p>}<hr/><form action={assessPractical.bind(null,s.id)} className="form"><h3>{s.task.rubric.name}</h3><div className="grid grid-2">{s.task.rubric.criteria.map(c=><div className="field" key={c.id}><label>{c.label} (0–{c.maxScore})</label><input className="input" type="number" min="0" max={c.maxScore} step="0.5" name={`criterion_${c.id}`} required/><span className="small muted">{c.description}</span></div>)}</div><div className="field"><label>Feedback</label><textarea className="textarea" name="feedback" required/></div><div className="field"><label>Decision</label><select className="select" name="decision"><option value="ASSESSED">Assessment complete</option><option value="NEEDS_REVISION">Needs revision / resubmission</option></select></div><button className="btn btn-primary">Save assessment</button></form></div>)}
 {projects.map(s=><div className="card" key={s.id}><div className="inline"><span className="badge badge-yellow">Final project</span><span className="badge">{s.hardwarePlatform.name}</span><span className="badge">Attempt {s.submissionNo}</span><span className="badge">{formatDate(s.submittedAt)}</span></div><h2 style={{fontSize:26,marginTop:12}}>{s.student.displayName} — {s.project.title}</h2><p className="muted">{s.studentNotes}</p>{s.troubleshootingNotes?<p className="small muted"><strong>Troubleshooting:</strong> {s.troubleshootingNotes}</p>:null}{s.codeSnippet?<pre className="code">{s.codeSnippet}</pre>:null}<div className="inline">{s.evidence.map(e=><a className="btn" href={`/api/evidence/${e.id}`} target="_blank" rel="noreferrer" key={e.id}>Open project evidence</a>)}</div><hr/><form action={assessProject.bind(null,s.id)} className="form"><h3>{s.project.rubric.name}</h3><div className="grid grid-2">{s.project.rubric.criteria.map(c=><div className="field" key={c.id}><label>{c.label} (0–{c.maxScore})</label><input className="input" type="number" min="0" max={c.maxScore} step="0.5" name={`criterion_${c.id}`} required/></div>)}</div><div className="field"><label>Feedback</label><textarea className="textarea" name="feedback" required/></div><div className="field"><label>Decision</label><select className="select" name="decision"><option value="ASSESSED">Assessment complete</option><option value="NEEDS_REVISION">Needs revision / resubmission</option></select></div><button className="btn btn-primary">Save project assessment</button></form></div>)}
 {submissions.length===0&&projects.length===0?<div className="card empty">No lesson or project submissions are waiting for review.</div>:null}</div></>;
}
