import { db } from "@/lib/db";
import { requireRole } from "@/lib/session";
import { formatDate, percent } from "@/lib/format";
import { startProject, submitProject } from "@/lib/learning-actions";
import { CompressedEvidenceInput } from "@/components/compressed-evidence-input";

export default async function StudentProjects() {
  const user = await requireRole("STUDENT");
  const assignments = await db.projectAssignment.findMany({
    where: { status: "ACTIVE", classroom: { enrollments: { some: { studentId: user.id, status: "ACTIVE" } } } },
    include: { classroom: true, project: { include: { rubric: { include: { criteria: { orderBy: { order: "asc" }, include: { skill: true } } } }, hardware: { include: { hardwarePlatform: true } }, submissions: { where: { studentId: user.id }, include: { assessment: true, evidence: true, hardwarePlatform: true }, orderBy: { submissionNo: "desc" } } } } },
  });
  const projectIds = assignments.map((assignment) => assignment.projectId);
  const starts = projectIds.length ? await db.learningEvent.findMany({ where: { learnerId: user.id, type: "PROJECT_STARTED", projectId: { in: projectIds } }, select: { projectId: true, attemptNo: true, hardwarePlatformId: true } }) : [];

  return <><div className="topbar"><div className="page-title"><div className="eyebrow">Projects</div><h1 style={{fontSize:38}}>Practical integration projects</h1><div className="muted">Project duration starts when you explicitly start an attempt, not when a page is opened.</div></div></div><div className="stack">{assignments.map((a) => {
    const nextAttempt = a.project.submissions.length + 1;
    const started = starts.find((event) => event.projectId === a.project.id && event.attemptNo === nextAttempt);
    return <div className="card" key={a.id}><div className="inline"><span className="badge">{a.classroom.name}</span><span className="badge">Due {formatDate(a.dueAt)}</span></div><h2 style={{fontSize:28,marginTop:12}}>{a.project.title}</h2><p className="muted">{a.project.description}</p><p>{a.project.instructions}</p><div className="small"><strong>Success criteria:</strong> {a.project.successCriteria}</div><div className="small muted" style={{marginTop:8}}>Compatible: {a.project.hardware.map((h) => h.hardwarePlatform.name).join(", ")}</div><hr/>
      {!started ? <form action={startProject.bind(null, a.project.id)} className="form"><div className="field"><label>Board you will use for attempt {nextAttempt}</label><select className="select" name="hardwarePlatformId" required>{a.project.hardware.map((h) => <option key={h.hardwarePlatformId} value={h.hardwarePlatformId}>{h.hardwarePlatform.name}</option>)}</select></div><button className="btn btn-primary">Start project attempt</button><div className="small muted">This records the first project-work timestamp for elapsed-time analytics.</div></form> : <form action={submitProject.bind(null, a.project.id)} className="form" encType="multipart/form-data"><div className="field"><label>Board used</label><select className="select" name="hardwarePlatformId" defaultValue={started.hardwarePlatformId ?? a.project.hardware[0]?.hardwarePlatformId} required>{a.project.hardware.map((h) => <option key={h.hardwarePlatformId} value={h.hardwarePlatformId}>{h.hardwarePlatform.name}</option>)}</select></div><CompressedEvidenceInput label="Project evidence photo or PDF"/><div className="field"><label>Build notes</label><textarea className="textarea" name="studentNotes" required/></div><div className="field"><label>Code</label><textarea className="textarea" name="codeSnippet"/></div><div className="field"><label>Troubleshooting attempts</label><textarea className="textarea" name="troubleshootingNotes" placeholder="Describe a fault, what you tested, and what changed." required/></div><button className="btn btn-primary">Submit project</button></form>}
      {a.project.submissions.length ? <div style={{marginTop:22}}><h3>Submission history</h3><div className="stack" style={{marginTop:10}}>{a.project.submissions.map((s) => <div className="card card-muted" key={s.id}><div className="inline"><span className="badge">Attempt {s.submissionNo}</span><span className={s.status === "ASSESSED" ? "badge badge-green" : s.status === "NEEDS_REVISION" ? "badge badge-yellow" : "badge"}>{s.status.replaceAll("_", " ")}</span><span className="badge">{s.hardwarePlatform.name}</span></div><p className="muted">{s.studentNotes}</p><div className="inline">{s.evidence.map((e) => <a className="btn" key={e.id} href={`/api/evidence/${e.id}`} target="_blank" rel="noreferrer">View evidence</a>)}</div>{s.assessment ? <div style={{marginTop:12}}><strong>Teacher score: {percent(s.assessment.totalScore, s.assessment.maxScore)}</strong><p>{s.assessment.feedback}</p></div> : null}</div>)}</div></div> : null}<hr/><h3>Project rubric</h3><ul className="list">{a.project.rubric.criteria.map((c) => <li key={c.id}>{c.label} — {c.maxScore} pts{c.skill ? ` · ${c.skill.name}` : ""}</li>)}</ul></div>;
  })}{assignments.length === 0 ? <div className="card empty">No projects assigned yet.</div> : null}</div></>;
}
