"use client";

import Link from "next/link";
import { useState } from "react";
import { HardwareImage } from "@/components/hardware-image";
import { monitorCode, monitorRubric, showcaseBoards } from "@/lib/showcase";

const parts = [["Microcontroller + data USB cable", "1", "Arduino Uno or classic ESP32-WROOM development board"], ["Solderless breadboard", "1", "Keep power rails and signal rows separate"], ["DHT22 temperature/humidity sensor", "1", "Choose a module rated for the selected supply"], ["Jumper wires", "8–12", "Use suitable male/female ends for your module"], ["Green LED + red LED", "1 each", "Long leg is normally the anode; verify polarity"], ["330 Ω resistor", "2", "One in series with each LED"], ["10 kΩ resistor", "1 if needed", "DATA pull-up; check whether the module already has one"]];
const questions = [
  { prompt: "The sensor reports a failed reading. What should you do first?", options: ["Increase the supply voltage", "Disconnect power and check the sensor wiring and type", "Mark the build complete"], correct: 1, explanation: "Check the supply, ground, DATA connection and configured sensor type. Change one thing at a time." },
  { prompt: "Why record at least three readings?", options: ["To check stability and changing conditions", "To increase GPIO current", "To avoid teacher review"], correct: 0, explanation: "Several readings help you distinguish a pattern from one unusual value. Record real values and units." },
  { prompt: "What establishes practical success in a classroom lesson?", options: ["Opening this page", "An AI response", "Evidence of the build and teacher assessment"], correct: 2, explanation: "Instructions and self-checks support learning. Practical completion requires evidence and teacher review." },
];

export function MonitorShowcase() {
  const [board, setBoard] = useState<keyof typeof showcaseBoards>("uno");
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const b = showcaseBoards[board];
  const sections = ["Introduction", "Components", "Safety", "Wiring", "Code", "Run test", "Record readings", "Troubleshoot", "Knowledge check", "Evidence", "Teacher rubric", "Next steps"];
  return <main id="main" className="sample-page">
    <section className="sample-hero"><div className="container"><p className="eyebrow">A STEMBuild sample lesson · No account needed</p><h1>Smart Environment<br /><span>Monitor</span></h1><p className="lead">Build a sensor circuit, read temperature and humidity, and explain what your measurements mean.</p><div className="inline"><span className="badge">Beginner · about 90 minutes</span><span className="badge">Arduino Uno / ESP32</span><span className="badge">Teacher-supervised build</span></div><div className="actions"><a href="#step-1" className="btn btn-primary">Start the sample lesson</a><Link href="/teachers" className="btn">Plan a classroom session</Link></div><p className="small muted">This public sample does not create an account, save answers or award completion. Assigned classroom lessons are available after sign-in. For offline use, open this sample and download the code and log while connected; availability depends on this browser keeping its saved files.</p></div></section>
    <div className="container sample-layout"><aside className="sample-toc"><nav aria-label="Lesson steps"><strong>Your build path</strong>{sections.map((s, i) => <a key={s} href={`#step-${i + 1}`}><span>{String(i + 1).padStart(2, "0")}</span>{s}</a>)}</nav></aside><div className="sample-content">
      <section id="step-1" className="card"><p className="eyebrow">01 · Introduction</p><h2>From a measurement to information</h2><p>A sensor measures temperature and relative humidity. Your program checks the reading, prints it and switches an LED when an example threshold is crossed.</p><h3>By the end, you should be able to</h3><ul className="list"><li>Wire the selected board and sensor safely.</li><li>Explain the code and the difference between °C and relative humidity (%).</li><li>Record three readings and investigate an unexpected result.</li><li>Present evidence that a teacher can assess.</li></ul></section>
      <section id="step-2" className="card"><p className="eyebrow">02 · Components</p><h2>Choose your board</h2><div className="grid grid-2 board-options" role="group" aria-label="Choose sample board">{Object.entries(showcaseBoards).map(([key, value]) => <button type="button" key={key} className={`board-choice ${board === key ? "selected" : ""}`} aria-pressed={board === key} onClick={() => setBoard(key as keyof typeof showcaseBoards)}><HardwareImage name={value.name} decorative /><strong>{value.name}</strong></button>)}</div><p role="status" className="small muted">Showing wiring and code for {b.name}. ESP32 pins below are for the classic ESP32, not C3/S3 boards.</p><div className="table-wrap"><table><caption>Parts for one shared kit</caption><thead><tr><th>Component</th><th>Quantity</th><th>Check</th></tr></thead><tbody>{parts.map(([part, count, note]) => <tr key={part}><td>{part}</td><td>{count}</td><td>{note}</td></tr>)}</tbody></table></div><p className="small muted">A buzzer is an optional later extension; it is not wired or driven in this sample. Use the same kit in pairs with rotating builder, programmer and recorder roles.</p><Link className="text-link small" href="/#boards">Board example models and photo credits</Link></section>
      <section id="step-3" className="card"><p className="eyebrow">03 · Safety</p><h2>Inspect before you power</h2><ul className="list"><li>Disconnect USB before moving wires. Ask a teacher to inspect the build before power-up.</li><li>Use a regulated USB supply through the development board. Do not connect mains electricity or a loose battery to this circuit.</li><li>Use one 330 Ω resistor per LED. Never bridge a supply rail to ground.</li><li>This {b.name} circuit uses a {b.voltage} sensor supply. Verify the exact module rating and printed VCC / DATA / GND labels; physical pin order varies.</li><li>For ESP32, keep DATA and its pull-up at 3.3 V. Do not connect a 5 V module signal to GPIO. If the sensor will not work at 3.3 V, stop and ask for a compatible module or reviewed level shifting.</li><li>Keep the sensor dry. The indicator is a classroom example, not a safety alarm.</li></ul></section>
      <section id="step-4" className="card"><p className="eyebrow">04 · Wiring · {b.name}</p><h2>Follow the signal labels</h2><p>Use the actual board pin labels rather than counting header positions. A bare four-pin DHT22 has an unused pin; three-pin modules may arrange signals differently.</p><div className="table-wrap"><table><caption>{b.name} connection map</caption><thead><tr><th>Component connection</th><th>Board connection</th></tr></thead><tbody><tr><td>DHT22 VCC</td><td>{board === "uno" ? "5V" : "3V3"}</td></tr><tr><td>DHT22 GND</td><td>GND</td></tr><tr><td>DHT22 DATA</td><td>{board === "uno" ? "D" : "GPIO"}{b.sensorPin}</td></tr><tr><td>Green LED anode through 330 Ω</td><td>{board === "uno" ? "D" : "GPIO"}{b.greenPin}</td></tr><tr><td>Red LED anode through 330 Ω</td><td>{board === "uno" ? "D" : "GPIO"}{b.redPin}</td></tr><tr><td>Both LED cathodes</td><td>GND</td></tr><tr><td>10 kΩ DATA pull-up, if required</td><td>Between DATA and the selected {b.voltage} sensor supply</td></tr></tbody></table></div><p className="small muted">Check continuity with power off if a meter is available. Keep wires short and confirm whether breadboard power rails are split.</p></section>
      <section id="step-5" className="card"><p className="eyebrow">05 · Code</p><h2>Read, then upload</h2><p>In Arduino IDE, install Adafruit’s DHT sensor library and its Adafruit Unified Sensor dependency. For ESP32, also install Espressif’s board support and select your exact development board.</p><p>This sample uses <strong>DHT22</strong>. For a DHT11, change SENSOR_TYPE to DHT11 only after checking its voltage requirements and wiring. An assigned lesson may use a different sensor configuration.</p><a className="btn" href={`/lessons/${b.file}`} download>Download {b.name} code</a><pre className="code"><code>{monitorCode(board)}</code></pre><p className="small muted">Trace SENSOR_PIN, the invalid-reading check and aboveThreshold. The example thresholds are 30 °C and 75% RH.</p></section>
      <section id="step-6" className="card"><p className="eyebrow">06 · Run test</p><h2>Observe the actual result</h2><ol className="list"><li>Have the circuit inspected, then connect USB.</li><li>Select {b.name === "ESP32" ? "your exact classic ESP32 board" : b.name} and the USB port. Verify the sketch, then upload.</li><li>Open Serial Monitor at <strong>{b.baud} baud</strong>. Wait for several readings.</li><li>Green means a valid reading below both example thresholds. Steady red means a valid reading above at least one threshold. Flashing red with a failure message means a sensor fault.</li><li>Warm the air nearby with your hand without touching or wetting the sensor; observe whether readings change. Do not use a flame or heater.</li></ol><p className="notice">A successful upload is not proof of a working sensor. Record what you actually observe; there are no simulated live readings here.</p></section>
      <section id="step-7" className="card"><p className="eyebrow">07 · Record readings</p><h2>Keep a small test log</h2><p>Record at least three readings about 10 seconds apart. Include the board, sensor model, time, temperature (°C), humidity (%), LED state and observations.</p><a href="/lessons/reading-log.csv" download className="btn">Download blank reading log</a><p>Compare the readings. Could a change come from the environment, loose wiring or the sensor’s limitations? Explain your reasoning rather than copying an expected value.</p></section>
      <section id="step-8" className="card"><p className="eyebrow">08 · Troubleshoot</p><h2>Change one thing at a time</h2>{[["No Serial Monitor output", "Check the selected USB port, data-capable cable and baud rate before changing the circuit."], ["Read failed / NaN", "Disconnect power. Check VCC, GND, DATA, the pull-up and DHT22 configuration. Reconnect and wait for the next measurement."], ["LED does not respond", "Disconnect power and check polarity, series resistor and the selected GPIO. Compare the actual value with the threshold."], ["Unexpected readings", "Keep the sensor dry, inspect loose jumpers and compare repeated measurements. Do not assume a single value is accurate."]].map(([title, text]) => <details className="sample-details" key={title}><summary>{title}</summary><p>{text}</p></details>)}<p className="small muted">Write down the symptom → one check or change → observed result. If unresolved, report it honestly.</p></section>
      <section id="step-9" className="card"><p className="eyebrow">09 · Knowledge check</p><h2>Check your understanding</h2><p className="muted">Practice only. Answers stay on this page and are not recorded as classroom progress.</p>{questions.map((q, i) => <fieldset className="sample-question" key={q.prompt}><legend>{q.prompt}</legend>{q.options.map((option, j) => <label key={option}><input type="radio" name={`sample-question-${i}`} checked={answers[i] === j} onChange={() => setAnswers((previous) => ({ ...previous, [i]: j }))} />{option}</label>)}{answers[i] !== undefined && <p role="status" className={answers[i] === q.correct ? "sample-correct" : "muted"}>{answers[i] === q.correct ? "Correct. " : "Try again. "}{q.explanation}</p>}</fieldset>)}</section>
      <section id="step-10" className="card"><p className="eyebrow">10 · Evidence</p><h2>Show what you built</h2><ul className="list"><li>A clear photo of the circuit with board and sensor identified.</li><li>Serial output or a log of three actual measurements.</li><li>The code you used, your explanation of the indicator and a troubleshooting note.</li><li>Any unresolved issue and what you would test next.</li></ul><p>In an assigned classroom lesson, sign in to submit evidence. Avoid pupil faces, names and unrelated personal information in photographs. Teachers review the result; this public sample does not accept uploads.</p><Link href="/login" className="btn btn-primary">Sign in for assigned lessons</Link></section>
      <section id="step-11" className="card"><p className="eyebrow">11 · Teacher rubric</p><h2>How practical skills are assessed</h2><p>Sample rubric: six criteria, each scored 0–4 (24 possible points). A teacher evaluates evidence, asks for revisions where needed and provides feedback.</p><dl className="sample-rubric">{monitorRubric.map(([title, description]) => <div key={title}><dt>{title}</dt><dd>{description}</dd></div>)}</dl><p className="small muted">0: not evidenced · 1: substantial support needed · 2: partly demonstrated · 3: demonstrated with minor support · 4: independently demonstrated and explained. Missing evidence does not prove inability; request a further demonstration.</p></section>
      <section id="step-12" className="card"><p className="eyebrow">12 · Next steps</p><h2>Take the lesson into your classroom</h2><p>Assigned lessons connect attempts, quizzes, evidence and rubric feedback to teacher analytics. AI guidance can suggest checks, but cannot approve practical completion.</p><p>For an ESP32 extension, plan how to send validated measurements with a device identifier, units and timestamp. Live hardware ingestion is a future extension, not a feature of this sample.</p><div className="actions"><Link href="/teachers" className="btn btn-primary">Teacher setup guide</Link><Link href="/about" className="btn">Our impact plan</Link><button className="btn" type="button" onClick={() => window.print()}>Print this lesson</button></div><details className="sample-details"><summary>Hardware references</summary><ul className="list"><li><a className="text-link" href="https://learn.adafruit.com/dht/connecting-to-a-dhtxx-sensor" target="_blank" rel="noreferrer">Adafruit: DHT sensor connections</a></li><li><a className="text-link" href="https://docs.espressif.com/projects/esp-faq/en/latest/hardware-related/hardware-design.html" target="_blank" rel="noreferrer">Espressif: hardware design guidance</a></li></ul></details></section>
    </div></div>
  </main>;
}
