import { StatCard } from "@/components/stat-card";
import { getTeacherLearningAnalytics } from "@/lib/analytics";
import { formatDuration, percentRatio } from "@/lib/format";
import { requireRole } from "@/lib/session";

export default async function TeacherAnalytics() {
  const teacher = await requireRole("TEACHER");
  const analytics = await getTeacherLearningAnalytics(teacher.id);
  if (!analytics) return null;
  const needsAttention = analytics.learnerRows.filter((row) => row.needsAttention);
  const codingVsWiring = analytics.learnerRows.filter((row) => row.codingStrongWiringWeak);
  const repeatedHints = analytics.learnerRows.filter((row) => row.repeatedHints);

  return <>
    <div className="topbar"><div className="page-title"><div className="eyebrow">Learning engineering</div><h1 style={{fontSize:38}}>Class learning analytics from stored events</h1><div className="muted">No page-view metrics and no generated AI conclusions. Every value below is derived from learner attempts, rubric scores, hints, troubleshooting and completion events.</div></div></div>
    <div className="grid grid-4"><StatCard label="Learners" value={analytics.learnerRows.length}/><StatCard label="Recorded learning events" value={analytics.events.length}/><StatCard label="Quiz pass rate" value={percentRatio(analytics.assessment.quizPassRate)}/><StatCard label="Practical pass rate" value={percentRatio(analytics.assessment.practicalPassRate)}/></div>

    <section className="section"><div className="section-title"><div><h2>Which students are struggling?</h2><div className="muted">Transparent rule: practical mastery below 70% with at least two scores, two or more failed/revision outcomes, or three or more hint/troubleshooting events.</div></div></div><div className="table-wrap"><table><thead><tr><th>Learner</th><th>Practical mastery</th><th>Failed / revision</th><th>Hints</th><th>Troubleshooting</th><th>Trend</th></tr></thead><tbody>{needsAttention.map((row) => <tr key={row.id}><td><strong>{row.displayName}</strong></td><td>{percentRatio(row.practicalMastery)}</td><td>{row.failedOutcomes}</td><td>{row.hints}</td><td>{row.troubleshooting}</td><td>{row.trend.label}{row.trend.delta == null ? "" : ` (${row.trend.delta >= 0 ? "+" : ""}${Math.round(row.trend.delta * 100)} pts)`}</td></tr>)}{needsAttention.length === 0 ? <tr><td colSpan={6} className="muted">No learner currently meets the documented attention rule.</td></tr> : null}</tbody></table></div></section>

    <section><h2>Skill mastery view</h2><p className="muted">Practical mastery comes from teacher rubric events. Knowledge mastery comes from quiz-answer events. They remain separate so a quiz does not hide a hands-on skill gap.</p><div className="grid grid-3" style={{marginTop:14}}>{analytics.classSkillMastery.map((skill) => <div className="card card-muted" key={skill.id}><div className="small muted">{skill.name}</div><div className="metric">{percentRatio(skill.overallMastery)}</div><div className="small muted">Practical {percentRatio(skill.practicalMastery)} · Knowledge {percentRatio(skill.knowledgeMastery)}</div><div className="small muted" style={{marginTop:7}}>{skill.evidenceCount} scored evidence event{skill.evidenceCount === 1 ? "" : "s"}</div></div>)}</div></section>

    <section className="section"><h2>Specific patterns teachers asked for</h2><div className="grid grid-2" style={{marginTop:14}}><div className="card"><h3>Coding stronger than wiring</h3><p className="small muted">Requires at least two practical rubric scores in both skills, coding ≥70% and circuit building &lt;60%.</p><div className="stack" style={{marginTop:12}}>{codingVsWiring.map((row) => <div className="card card-muted" key={row.id}><strong>{row.displayName}</strong><div className="small muted">Microcontroller programming {percentRatio(row.mastery.find((s) => s.slug === "microcontroller-programming")?.practicalMastery)} · Circuit building {percentRatio(row.mastery.find((s) => s.slug === "circuit-building")?.practicalMastery)}</div></div>)}{codingVsWiring.length === 0 ? <div className="muted">No current learner meets this rule.</div> : null}</div></div><div className="card"><h3>Repeated hint requests</h3><p className="small muted">Shown after three or more recorded hint requests.</p><div className="stack" style={{marginTop:12}}>{repeatedHints.map((row) => <div className="card card-muted" key={row.id}><strong>{row.displayName}</strong><div className="small muted">{row.hints} hints · {row.troubleshooting} troubleshooting records</div></div>)}{repeatedHints.length === 0 ? <div className="muted">No learner has reached the repeated-hint threshold.</div> : null}</div></div></div></section>

    <section><h2>Lesson difficulty analytics</h2><p className="muted">Failure rate uses completed quiz attempts and teacher-reviewed practical attempts. Average duration uses explicit learner start → submit/complete timestamps.</p><div className="table-wrap" style={{marginTop:14}}><table><thead><tr><th>Lesson</th><th>Attempts</th><th>Failed/revision</th><th>Failure rate</th><th>Avg duration</th><th>Hints</th><th>Troubleshooting</th></tr></thead><tbody>{analytics.lessonDifficulty.map((row) => <tr key={row.lessonId}><td>{row.lessonTitle}</td><td>{row.attempts}</td><td>{row.failed}</td><td>{percentRatio(row.failureRate)}</td><td>{formatDuration(row.averageDurationMs)}</td><td>{row.hints}</td><td>{row.troubleshooting}</td></tr>)}{analytics.lessonDifficulty.length === 0 ? <tr><td colSpan={7} className="muted">Lesson difficulty appears after learners generate attempt events.</td></tr> : null}</tbody></table></div></section>

    <section className="section"><h2>Assessment analytics</h2><div className="grid grid-4" style={{marginTop:14}}><StatCard label="Quiz attempts" value={analytics.assessment.quizAttempts}/><StatCard label="Average quiz score" value={percentRatio(analytics.assessment.averageQuizScore)}/><StatCard label="Practical reviews" value={analytics.assessment.practicalReviews}/><StatCard label="Average practical score" value={percentRatio(analytics.assessment.averagePracticalScore)}/></div><div className="card" style={{marginTop:16}}><div className="eyebrow">Practical project time</div><div className="metric">{formatDuration(analytics.assessment.averageProjectDurationMs)}</div><div className="small muted">Average elapsed time from an explicit project-start event to submission. It is not claimed to be continuous active working time.</div></div></section>

    <section><h2>Hardware difficulty signals</h2><p className="muted">These are counts, not an AI ranking. A difficulty signal is a failed/revision review, hint request or troubleshooting event associated with that platform.</p><div className="table-wrap" style={{marginTop:14}}><table><thead><tr><th>Platform</th><th>Attempts</th><th>Failed/revision</th><th>Hints</th><th>Troubleshooting</th><th>Total signals</th></tr></thead><tbody>{analytics.hardwareDifficulty.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.attempts}</td><td>{row.failed}</td><td>{row.hints}</td><td>{row.troubleshooting}</td><td>{row.difficultySignals}</td></tr>)}{analytics.hardwareDifficulty.length === 0 ? <tr><td colSpan={6} className="muted">Hardware analytics appear after hardware-linked learner events exist.</td></tr> : null}</tbody></table></div></section>

    <section className="section"><h2>Are learners improving over time?</h2><p className="muted">Trend compares the average normalized score in the first half of a learner&apos;s scored events with the second half. At least four scored events are required. ±10 percentage points is the improvement/decline threshold.</p><div className="table-wrap" style={{marginTop:14}}><table><thead><tr><th>Learner</th><th>Trend</th><th>Change</th><th>Scored events</th></tr></thead><tbody>{analytics.learnerRows.map((row) => <tr key={row.id}><td>{row.displayName}</td><td>{row.trend.label}</td><td>{row.trend.delta == null ? "—" : `${row.trend.delta >= 0 ? "+" : ""}${Math.round(row.trend.delta * 100)} pts`}</td><td>{row.trend.samples}</td></tr>)}</tbody></table></div></section>
  </>;
}
